---
- name: Configurar servidor Nginx con PHP
  hosts: web
  become: true

  tasks:
    - name: Actualizar apt
      apt:
        update_cache: yes

    - name: Instalar Nginx y PHP-FPM
      apt:
        name:
          - nginx
          - php-fpm
          - php-mysql
        state: present

    - name: Asegurar que Nginx esté activo
      service:
        name: nginx
        state: started
        enabled: true

    - name: Configurar sitio por defecto de Nginx para PHP
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;

              root /var/www/html;
              index index.php index.html index.htm;

              server_name _;

              location / {
                  try_files $uri $uri/ =404;
              }

              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
              }

              location ~ /\.ht {
                  deny all;
              }
          }
      notify: Restart nginx

    - name: Crear archivo PHP de prueba
      copy:
        dest: /var/www/html/info.php
        content: |
          <?php
          phpinfo();
          ?>

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
